name: Deploy to Production

on:
  push:
    tags:
      - 'v*'

jobs:
  call-test:
    uses: ./.github/workflows/test.yml

  deploy-prod:
    needs: call-test
    runs-on: ubuntu-latest
    if: ${{ needs.call-test.result == 'success' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Poetry
        run: pip install poetry poetry-plugin-export

      - name: Install dependencies
        run: poetry install

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Install Serverless Framework and plugins
        run: |
          npm install -g serverless@3
          serverless plugin install -n serverless-python-requirements

      - name: Deploy to production
        run: make deploy-serverless-prod 